spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssafy.seoul3
    password: tjdnfTkvl3qks
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true